### ISSUE TITLE
NoMethodError when trying to generate a cheatset

### ISSUE THREAD

**Issue by yukiyan** [Kapeli/cheatset#16]
It said I successfully installed cheatset , and when I try to generate the sample docset you guys gave, it throws this exception.

```ruby
% cheatset generate sample.rb
/Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge/lexers/apache.rb:15:in `<class:Apache>': private method `load' called for Psych:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge/lexers/apache.rb:5:in `<module:Lexers>'
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge/lexers/apache.rb:4:in `<module:Rouge>'
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge/lexers/apache.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge.rb:43:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge.rb:43:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge.rb:43:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/rouge-1.7.7/lib/rouge.rb:43:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cheatset-1.2.19/lib/cheatset/dsl/base.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cheatset-1.2.19/lib/cheatset.rb:5:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cheatset-1.2.19/lib/cheatset.rb:4:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/cheatset-1.2.19/lib/cheatset.rb:4:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cheatset-1.2.19/bin/cheatset:4:in `<top (required)>'
	from /usr/bin/cheatset:23:in `load'
	from /usr/bin/cheatset:23:in `<main>'
```

My Ruby version is 2.2.0

```ruby
% rbenv local
2.2.0
```

**Comment by Kapeli** [comment]
No idea to be honest. This seems to be an issue with Ruby 2.2.0 as far as I can tell: https://github.com/chetan/psych_load_bug.

**Comment by yukiyan** [comment]
It works, when I tried `rbenv exec gem install cheatset` and `rbenv exec cheatset generate sample.rb` :+1:
It seems to be rbenv problem.

`gem install cheatset` and `cheatset generate sample.rb` is still returned NoMethodError.

Thank you for your appreciate:bow:
